site_name: Potato Head
site_url: https://demml.github.io/potatohead/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-night
        name: dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-sunny
        name: light mode

  features:
    - navigation.sections
    - toc.follow
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/potatohead.svg"

repo_name: potatohead
repo_url: https://github.com/demml/potatohead
edit_uri: edit/main/docs/

nav:
  - Overview: "index.md"
  - Quickstart: "quickstart.md"

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings

extra_css:
  - css/custom.css
  - stylesheets/extra.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
