[package]
name = "potato-types"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "Toppings for your potatoes"
license = "MIT"

[lib]
doctest = false

[dependencies]
pyo3 = { workspace = true }
potato-utils = { workspace = true }