# mypy: disable-error-code="attr-defined"
# pylint: disable=no-name-in-module

from .._potato_head import (
    # Request - Schema and Safety
    SchemaType,
    Schema,
    HarmCategory,
    HarmBlockThreshold,
    HarmBlockMethod,
    SafetySetting,
    # Request - Modality and Media
    Modality,
    MediaResolution,
    ModelRoutingPreference,
    ThinkingLevel,
    ImageConfig,
    # Request - Routing
    AutoRoutingMode,
    ManualRoutingMode,
    RoutingConfigMode,
    RoutingConfig,
    # Request - Speech/Voice
    PrebuiltVoiceConfig,
    VoiceConfig,
    SpeakerVoiceConfig,
    MultiSpeakerVoiceConfig,
    SpeechConfig,
    # Request - Generation and Configuration
    GenerationConfig,
    ModelArmorConfig,
    Mode,
    FunctionCallingConfig,
    LatLng,
    RetrievalConfig,
    ToolConfig,
    GeminiSettings,
    # Request - Code and Functions
    Language,
    Outcome,
    FileData,
    PartialArgs,
    FunctionCall,
    Blob,
    FunctionResponse,
    ExecutableCode,
    CodeExecutionResult,
    # Request - Content Parts
    VideoMetadata,
    PartMetadata,
    Part,
    GeminiContent,
    # Request - Tools and Functions
    Behavior,
    FunctionDeclaration,
    # Request - Retrieval
    DataStoreSpec,
    VertexAISearch,
    VertexRagStore,
    RagResource,
    RagRetrievalConfig,
    Filter,
    RankService,
    LlmRanker,
    RankingConfig,
    Ranking,
    # Request - External API
    ApiSpecType,
    SimpleSearchParams,
    ElasticSearchParams,
    AuthType,
    HttpElementLocation,
    ApiKeyConfig,
    HttpBasicAuthConfig,
    GoogleServiceAccountConfig,
    OauthConfigValue,
    OauthConfig,
    OidcConfig,
    AuthConfigValue,
    AuthConfig,
    ExternalApi,
    RetrievalSource,
    Retrieval,
    # Request - Search
    Interval,
    GoogleSearch,
    PhishBlockThreshold,
    VertexGoogleSearch,
    EnterpriseWebSearch,
    ParallelAiSearch,
    GoogleSearchNum,
    DynamicRetrievalMode,
    DynamicRetrievalConfig,
    GoogleSearchRetrieval,
    GoogleMaps,
    # Request - Computer Use and Context
    CodeExecution,
    ComputerUseEnvironment,
    ComputerUse,
    UrlContext,
    FileSearch,
    Tool,
    # Response - Usage and Metadata
    TrafficType,
    ModalityTokenCount,
    UsageMetadata,
    BlockedReason,
    PromptFeedback,
    # Response - URL and Retrieval
    UrlRetrievalStatus,
    UrlMetadata,
    UrlContextMetadata,
    SourceFlaggingUri,
    RetrievalMetadata,
    # Response - Search and Grounding
    SearchEntryPoint,
    Segment,
    GroundingSupport,
    Web,
    PageSpan,
    RagChunk,
    RetrievedContext,
    Maps,
    GroundingChunkType,
    GroundingChunk,
    GroundingMetadata,
    # Response - Safety
    HarmProbability,
    HarmSeverity,
    SafetyRating,
    # Response - Candidates
    FinishReason,
    LogprobsCandidate,
    TopCandidates,
    LogprobsResult,
    GoogleDate,
    Citation,
    CitationMetadata,
    Candidate,
    GenerateContentResponse,
    # Embeddings
    PredictRequest,
    PredictResponse,
    EmbeddingTaskType,
    GeminiEmbeddingConfig,
    ContentEmbedding,
    GeminiEmbeddingResponse,
    # Aliased
    GeminiThinkingConfig as ThinkingConfig,
)

__all__ = [
    # Request - Schema and Safety
    "SchemaType",
    "Schema",
    "HarmCategory",
    "HarmBlockThreshold",
    "HarmBlockMethod",
    "SafetySetting",
    # Request - Modality and Media
    "Modality",
    "MediaResolution",
    "ModelRoutingPreference",
    "ThinkingLevel",
    "ThinkingConfig",
    "ImageConfig",
    # Request - Routing
    "AutoRoutingMode",
    "ManualRoutingMode",
    "RoutingConfigMode",
    "RoutingConfig",
    # Request - Speech/Voice
    "PrebuiltVoiceConfig",
    "VoiceConfig",
    "SpeakerVoiceConfig",
    "MultiSpeakerVoiceConfig",
    "SpeechConfig",
    # Request - Generation and Configuration
    "GenerationConfig",
    "ModelArmorConfig",
    "Mode",
    "FunctionCallingConfig",
    "LatLng",
    "RetrievalConfig",
    "ToolConfig",
    "GeminiSettings",
    # Request - Code and Functions
    "Language",
    "Outcome",
    "FileData",
    "PartialArgs",
    "FunctionCall",
    "Blob",
    "FunctionResponse",
    "ExecutableCode",
    "CodeExecutionResult",
    # Request - Content Parts
    "VideoMetadata",
    "PartMetadata",
    "Part",
    "GeminiContent",
    # Request - Tools and Functions
    "Behavior",
    "FunctionDeclaration",
    # Request - Retrieval
    "DataStoreSpec",
    "VertexAISearch",
    "VertexRagStore",
    "RagResource",
    "RagRetrievalConfig",
    "Filter",
    "RankService",
    "LlmRanker",
    "RankingConfig",
    "Ranking",
    # Request - External API
    "ApiSpecType",
    "SimpleSearchParams",
    "ElasticSearchParams",
    "AuthType",
    "HttpElementLocation",
    "ApiKeyConfig",
    "HttpBasicAuthConfig",
    "GoogleServiceAccountConfig",
    "OauthConfigValue",
    "OauthConfig",
    "OidcConfig",
    "AuthConfigValue",
    "AuthConfig",
    "ExternalApi",
    "RetrievalSource",
    "Retrieval",
    # Request - Search
    "Interval",
    "GoogleSearch",
    "PhishBlockThreshold",
    "VertexGoogleSearch",
    "EnterpriseWebSearch",
    "ParallelAiSearch",
    "GoogleSearchNum",
    "DynamicRetrievalMode",
    "DynamicRetrievalConfig",
    "GoogleSearchRetrieval",
    "GoogleMaps",
    # Request - Computer Use and Context
    "CodeExecution",
    "ComputerUseEnvironment",
    "ComputerUse",
    "UrlContext",
    "FileSearch",
    "Tool",
    # Response - Usage and Metadata
    "TrafficType",
    "ModalityTokenCount",
    "UsageMetadata",
    "BlockedReason",
    "PromptFeedback",
    # Response - URL and Retrieval
    "UrlRetrievalStatus",
    "UrlMetadata",
    "UrlContextMetadata",
    "SourceFlaggingUri",
    "RetrievalMetadata",
    # Response - Search and Grounding
    "SearchEntryPoint",
    "Segment",
    "GroundingSupport",
    "Web",
    "PageSpan",
    "RagChunk",
    "RetrievedContext",
    "Maps",
    "GroundingChunkType",
    "GroundingChunk",
    "GroundingMetadata",
    # Response - Safety
    "HarmProbability",
    "HarmSeverity",
    "SafetyRating",
    # Response - Candidates
    "FinishReason",
    "LogprobsCandidate",
    "TopCandidates",
    "LogprobsResult",
    "GoogleDate",
    "Citation",
    "CitationMetadata",
    "Candidate",
    "GenerateContentResponse",
    # Embeddings
    "PredictRequest",
    "PredictResponse",
    "EmbeddingTaskType",
    "GeminiEmbeddingConfig",
    "ContentEmbedding",
    "GeminiEmbeddingResponse",
]
